### ISSUE TITLE
Getting a gfx Texture from an Image or Canvas

### ISSUE THREAD

**Issue by t-veor** [ggez/ggez#637]
Hello, I've been trying to use the [imgui-rs](https://github.com/Gekkio/imgui-rs) crate with ggez, and one of the problems I've run into is how to draw dynamically generated images.

I would like to render a bunch of whatever into a `Canvas`, and then pass the `Canvas` to imgui as a texture. I couldn't figure out how to do the second part; I am using `imgui_gfx_renderer`, where to render textures you have to insert `(ShaderResourceView<gfx_device_gl::Resources, [f32; 4]>, Sampler<gfx_device_gl::Resources>)` tuples into map on the renderer and pass the ids it gives back to imgui-rs, but none of the fields that could help me get either one of these types are public on `Image` or `Canvas`.

Initially I noticed that `graphics::set_canvas` modifies `ctx.gfx_context.data.out`, which I could get with `graphics::screen_render_target`, so I could hackily use this to get a reference to the render target underlying a `Canvas`; unfortunately this only gets me a `RawRenderTargetView` which I couldn't figure out how I could get back to a `ShaderResourceView`.

The next thing I thought of was possibly making my own `gfx_core::handle::Texture`, but it doesn't look like there's a way to just manually set a `RenderTargetView` for ggez, so in order to render arbitrary graphics onto my texture I'd need to reimplement the rendering operations outside of ggez and at this point I might as well be just using gfx. I also don't have access to the current sampler mode, because `gfx_context` is not public.

Apologies if there is a way to do this that I've missed, but I've done some searches and couldn't find any similar issues.

**Comment by icefoxen** [comment]
Nope, looks like you're the first person to want this!  Congrats!

Looks like your hacky solution would work; you can turn a `RawRenderTargetView` into a `RawShaderResourceView` via [`Factory::view_texture_as_shader_resource_raw()`](https://docs.rs/gfx/0.18.1/gfx/trait.Factory.html#tymethod.view_texture_as_shader_resource_raw), and then [`ggez::graphics::BackendSpec::raw_to_typed_shader_resource()`](https://docs.rs/ggez/0.5.0-rc.2/ggez/graphics/trait.BackendSpec.html#method.raw_to_typed_shader_resource) will do exactly what it says on the tin (using an undocumented gfx-rs API that was intended to be replaced but probably now never will be).

So that approach would PROBABLY work.

Of course, the easy way would be to add an `Image::get_raw_texture()` method, so that would work too.  Pulling it out of `ctx.gfx_context.data.out` is punching through like, two layers of abstraction.  Not awake enough to determine which is actually better.

**Comment by t-veor** [comment]
Aaah, because of my gfx-noobiness I missed that you could just turn a `RawRenderTargetView` into a `RawTexture` and then convert the `RawShaderResourceView` back into a `ShaderResourceView`. There's still a couple of problems with this, like needing to keep a copy of `conf` around so I can set up my `ResourceDesc` exactly like ggez does it (which I'm sure will never change) and not being able to grab the default `SamplerInfo`.

I think after going through this insanity it would've been easier if I just implemented my own imgui-rs renderer over top of ggez, haha.

**Comment by icefoxen** [comment]
Can't *imagine* how you could have missed that!  gfx-rs is super simple and all the interactions between its parts are completely obvious, right? :wink: 

`ResourceDesc` actually probably won't change, actually, but yeah it's still not great.  I have to ask, have you tried just pulling [`ggez`'s gfx renderer objects out](https://docs.rs/ggez/0.5.0-rc.2/ggez/graphics/fn.gfx_objects.html) and seeing if they fit into the [imgui-rs gfx renderer](https://github.com/Gekkio/imgui-rs/tree/master/imgui-gfx-renderer)?  Never used it before, and I'm not sure it would make the goal of "render something in ggez and then stick it onto a GUI element" any easier, but it might be worth looking at before you write your own full renderer.

**Comment by t-veor** [comment]
Yeah, I'd already had that set up by following https://github.com/iolivia/imgui-ggez-starter, and was using it to render other UI elements before encountering the problem of how to render actual textures.

The way imgui_gfx_renderer has it set up is you have to register textures in the renderer into its own hashmap, and then when it receives a texture ID to render frmo imgui it looks it up in its map to find the corresponding texture. I then sat there for an hour and a half or so figuring out how I was supposed to pass textures into it before giving up and calling it a night.

**Comment by t-veor** [comment]
I can probably close this issue, but having a `Image::get_raw_texture` or rather a `Canvas::get_raw_texture` so I can draw to it and not have to register a new texture would probably be pretty swell. It would definitely be better than this hack which basically works by exploiting the side effects of two different functions, along with defeating any kind of encapsulation you had around gfx.

I understand that it's probably not great to expose backend details since probably you want that to be opaque to consumers of ggez, but you already expose your innards with `graphics::gfx_objects` and there's inevitably going to be more use cases which will need more than the API you've wrapped around with. Maybe this is a discussion you've already had. Regardless, thanks a lot for your help 😄

**Comment by icefoxen** [comment]
Yeah, I'm not sure whether I would want to have an `Image::get_raw_texture`...  I'm not necessarily entirely against it though, and I haven't had this discussion with anyone, so feel free to have it if you want.  What MIGHT be doable is to make a submodule that contains extension traits that expose these things, so you could import `ggez::guts::ImageRaw` to get `Image::get_raw_texture()` and such, while most people would just ignore it.  There would be no promise of a stable API though.

Really though, at some point you might be better off writing your own renderer, or just forking ggez and modifying it to add what you want.  The problem isn't so much that I don't want these things, but more that it increases the maintenance burden (even with minimal support) and it adds more stuff for newbies to sort through to figure out what they actually want.  I'm open to ideas of how to make this better.

**Comment by iolivia** [comment]
hey @t-veor, not sure if it helps, but I added images to https://github.com/iolivia/imgui-ggez-starter checkout out this PR 13. it's slightly different to what you want because it's just static images rather than a render of the ggez canvas, although that would be cool to add as an example as well.
